export const GET_ELE_REQUEST = 'GET_ELE_REQUEST';
export const GET_ELE_SUCCESS = 'GET_ELE_SUCCESS';
export const GET_ELE_FAIL = 'GET_ELE_FAIL';

export const GET_MANUAL_REQUEST = 'GET_MANUAL_REQUEST';
export const GET_MANUAL_SUCCESS = 'GET_MANUAL_SUCCESS';
export const GET_MANUAL_FAIL = 'GET_MANUAL_FAIL';

export const GET_ONLINE_REQUEST = 'GET_ONLINE_REQUEST ';
export const GET_ONLINE_SUCCESS = 'GET_ONLINE_SUCCESS';
export const GET_ONLINE_FAIL = ' GET_ONLINE_FAIL';

export const GET_ONLINE_ROOM_REQUEST = 'GET_ONLINE_ROOM_REQUEST';
export const GET_ONLINE_ROOM_SUCCESS = 'GET_ONLINE_ROOM_SUCCESS';
export const GET_ONLINE_ROOM_FAIL = 'GET_ONLINE_ROOM_FAIL';

export const GET_GUEST_REQUEST = 'GET_GUEST_REQUEST ';
export const GET_GUEST_SUCCESS = 'GET_GUEST_SUCCESS';
export const GET_GUEST_FAIL = 'GET_GUEST_FAIL ';

export const GET_ROOM_BOOKING_REQUEST = 'GET_ROOM_BOOKING_REQUEST';
export const GET_ROOM_BOOKING_SUCCESS = 'GET_ROOM_BOOKING_SUCCESS';
export const GET_ROOM_BOOKING_FAIL = 'GET_ROOM_BOOKING_FAIL';
